<a href="https://colab.research.google.com/github/valentinamoreno4321-cpu/matrices/blob/main/28_04_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Escritura de archivos desde python

In [1]:
# Crear y escribi mun archivo de texto
with open("archivo.txt", "w") as f:
    f.write("Hola, este es un archivo de texto.\n")
    f.write("Segunda linea.\n")

Con el argumento "w" se crea el archivo si no existe. Tambien sobreescribe el archivo si ya existe, borrando todo su contenido previo

Archivos txt.

In [2]:
with open("archivo.txt", "r") as f:
     print(f.read())

Hola, este es un archivo de texto.
Segunda linea.

Con el argumento "r" se leen archivos

In [3]:
from google.colab import files
files.download("archivo.txt")

In [4]:
#Abrir en modo append para editar un archivo ya existente
with open("archivo.txt", "a") as f:
    f.write("\nEsta es la nueva linea añadida.")

In [5]:
with open("archivo.txt", "r") as f:
     print(f.read())

Hola, este es un archivo de texto.
Segunda linea.

Esta es la nueva linea añadida.

In [6]:
with open("archivo1.txt", "w") as f:
    f.write("Hola, mi nombre es Valentina.\n")
    f.write("Tengo 21 años.\n")

In [7]:
with open("archivo1.txt", "r") as f:
     print(f.read())

Hola, mi nombre es Valentina.
Tengo 21 años.

In [8]:
from google.colab import files
files.download("archivo1.txt")

In [9]:
from google.colab import files
uploaded = files.upload()

Saving archivo1.txt to archivo1 (1).txt

In [10]:
with open("archivo1 (1).txt", "r") as f:
     print(f.read())

Hola, mi nombre es Valentina.
Tengo 21 años.

In [11]:
with open("archivo1 (1).txt","w") as f:
  f.write("Hola, soy Valentina.\n")
  f.write("Me gustan los perritos.\n")

In [12]:
with open("archivo1 (1).txt", "r") as f:
     print(f.read())

Hola, soy Valentina.
Me gustan los perritos.

In [14]:
from google.colab import files
files.download("archivo1 (1).txt")

Con archivos .csv

In [20]:
import csv

datos=[
    ["Nombre" , " Edad", "Ciudad"],
    ["Ana", 25, "Madrid"],
    ["Juan", 30, "Barcelona"],
    ["Camila", 27, "Valencia"]
]

with open ("datos.csv", "w", newline="") as f:
  writer = csv.writer(f)
  writer.writerows(datos)

In [21]:
with open("datos.csv", "r") as f:
     print(f.read())

Nombre, Edad,Ciudad
Ana,25,Madrid
Juan,30,Barcelona
Camila,27,Valencia

In [22]:
files.download("datos.csv")

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [24]:
ruta = "/content/drive/MyDrive/datos.csv"

import shutil
shutil.copy("datos.csv", ruta) # "datos csv": archivo de origen (en colab)

'/content/drive/MyDrive/datos.csv'

In [26]:
with open(ruta, "r") as f:
  data = list(csv.reader(f))

# Agregar nueva fila
data.append(["Valentina", 21, "Medellin"])
data

[['Nombre', ' Edad', 'Ciudad'],
 ['Ana', '25', 'Madrid'],
 ['Juan', '30', 'Barcelona'],
 ['Camila', '27', 'Valencia'],
 ['Valentina', 21, 'Medellin']]

In [29]:
# Guardar
with open(ruta, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(data)

# Mostrar después
print("\nDESPUÉS:")
with open(ruta, "r") as f:
    print(f.read())

DESPUÉS:
Nombre, Edad,Ciudad
Ana,25,Madrid
Juan,30,Barcelona
Camila,27,Valencia
Valentina,21,Medellin

In [ ]:
import os
os.listdir("content/drive/My")

In [32]:
import pandas as pd
df = pd.read_csv(ruta)
df

      Nombre   Edad     Ciudad
0        Ana     25     Madrid
1       Juan     30  Barcelona
2     Camila     27   Valencia
3  Valentina     21   Medellin

In [34]:
df["Nueva_Colombia"] = "valor"
df["Nueva_Colombia"] = [10,20,30, None]
df

      Nombre   Edad     Ciudad  Nueva_Colombia
0        Ana     25     Madrid            10.0
1       Juan     30  Barcelona            20.0
2     Camila     27   Valencia            30.0
3  Valentina     21   Medellin             NaN